## --- Book-specific options

book:
  title: "Building reproducible books with Bioconductor (template)"
  chapters:
    - index.qmd
    - pages/preamble.qmd
    - pages/Chapter-1.qmd
    - pages/Chapter-2.qmd
    - pages/Chapter-3.qmd
  cover-image: inst/assets/BiocBook.png
  favicon: inst/assets/bioc.png
  sidebar: 
    tools:
      - icon: git
        menu:
          - text: Source Code
            url:  https://github.com/js2264/BiocBook.template/
          - text: Browse version `devel`
            url:  https://js2264.github.io/BiocBook.template/devel/
    style: "docked"
    background: "light"
    border: true
    search: true
    collapse-level: 5
  search: 
    location: sidebar
  page-footer:
    background: light
    left: |
      This book was built with <a href="https://github.com/js2264/BiocBook/">BiocBook</a> with ❤️
  repo-branch: devel
  repo-actions: [edit, issue]
  open-graph: true

website:
  back-to-top-navigation: true

## --- Project-wide settings

project:
  type: book
  output-dir: docs

## --- Format options

format: 
  html:
    grid:
      sidebar-width: 500px
      body-width: 1100px
    theme: 
      - cosmo
      - inst/assets/book.scss
    highlight-style: atom-one
    code-link: true
    editor: visual
    citation-location: margin
    bibliography: inst/assets/bibliography.bib

## --- knitr options

knitr:
  opts_chunk: 
    collapse: true
    comment: "## " 
    cache: false
    fig.align: "center"
    python.reticulate: false
